development:
  adapter: mysql2
  encoding: utf8
  database: erep_development
  username: root
  password:
  # socket: /opt/lampp/var/mysql/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: erep_test
  username: root
  password:
  # socket: /opt/lampp/var/mysql/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: erep_production
  username: root
  password:
  # socket: /opt/lampp/var/mysql/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

